### ISSUE TITLE
QuakeML integration

### ISSUE THREAD

**Issue by cjhopp** [calum-chamberlain/EQcorrscan#23]
I'm going to go ahead and start working on QuakeML integration.

Read/write to and from Catalog classes should be straightforward via built in obspy methods, the more involved bit, I think, is creating new Event classes from new matched filter detections. 

What's the word on the features/location branch?

**Comment by calum-chamberlain** [comment]
The features/location branch is me playing with integrating a comparison between synthetic templates and detected events - I have also put in a WECC style picker (Waveform Envelope Cross-Correlation).  I'm not sure if these will ever make it to the master, they are not especially important I think.

Currently the matched-filter creates a DETECTION class for each one - I was thinking of changing the [PICK](https://github.com/calum-chamberlain/EQcorrscan/blob/master/eqcorrscan/utils/Sfile_util.py#L35) & [EVENTINFO](https://github.com/calum-chamberlain/EQcorrscan/blob/master/eqcorrscan/utils/Sfile_util.py#L182) and [DETECTION](https://github.com/calum-chamberlain/EQcorrscan/blob/master/eqcorrscan/core/match_filter.py#L66) classes to be the correct elements of obspys event class?

They would end up being thin wrappers around obspy.event, which would be simpler to write now, but might be more difficult to maintain than actually going in and changing how detections are stored to obspy.event.  That would be done in the match_filter function, which currently returns a list of DETECTION class things - It looks like changing it [there](https://github.com/calum-chamberlain/EQcorrscan/blob/master/eqcorrscan/core/match_filter.py#L587) wouldn't be so hard, but we might need some proprietary things, like cccsum value.  It would also need to be done in [brightness](https://github.com/calum-chamberlain/EQcorrscan/blob/master/eqcorrscan/core/match_filter.py#L587) and lag_calc, once lag_calc is written properly.

**Comment by cjhopp** [comment]
Alright, cool. So we should output the match_filter results to an obspy Catalog class. This should all still work in parallel with the Sfile functions though, right? What will need changing in the Sfile_utils in order to make the transition to obspy classes?

Also, where is EVENTINFO implemented? And is your version of PICK implemented anywhere but lag_calc?

**Comment by cjhopp** [comment]
Another thought: lag_calc might not be necessary if HypoDDpy were used instead? But for that to work I think we would need EQcorrscan to output QuakeML files which contain location information. Thoughts?

**Comment by calum-chamberlain** [comment]
PICK is implemented where I had the bright_lights link, but not in match_filter.  Ideally stile_util would read into obspy event class rather than the proprietary classes I wrote.

As for lag_calc/hypoDDpy - The way I do it, the lag_calc compares with a master event which gives the picks for the dt.ct file (so-called catalogue picks), these can then be located using any other software as well as fed into hypoDDpy, (or hypoDD).  You would usually use hypoDD with both dt.ct (catalogue) and dt.cc (cross-correlation) files, where the dt.cc compares everything with everything (rather than the one with many comparison I do for the dt.ct file).  I prefer that way, because you can compare location methods (by using the picks in multiple location algorithms).

As for location info in the quakeML files, that can be read in from the S-files, or other formats as we integrate them (for the template), and we can maybe lean on [obspyck's](https://github.com/megies/obspyck/wiki) integration with [NonLinLoc](https://github.com/megies/obspyck/blob/master/obspyck.py#L1970) and [Hypocentre2000](https://github.com/megies/obspyck/blob/master/obspyck.py#L1938) for detected event locations.  They have a couple of useful functions for converting their dicts to input files, which we could call on.

**Comment by calum-chamberlain** [comment]
I'm going to close this issue as we have now got the pull request active [here](https://github.com/calum-chamberlain/EQcorrscan/pull/24).
