### ISSUE TITLE
can't see plots after generating templates?

### ISSUE THREAD

**Issue by xiansch** [calum-chamberlain/EQcorrscan#28]
I would like to plot the cut templates after generating them, and I tried commenting out plt.close() in plotting.py's pretty_template_plot() afterward but nothing appears to show.  Setting save=True also doesn't seem to actually save the plots.  I am using Qt4Agg backend for matplotlib.

Thanks

**Comment by calum-chamberlain** [comment]
Can you give me a snippet of the code that you are using?

Do you see any warnings like:
UserWarning:  This call to matplotlib.use() has no effect because the backend has already been chosen;
This is often because the backend is set in match_filter to not show, as noted in the docs for [match_filter.match_filter](http://eqcorrscan.readthedocs.org/en/develop/submodules/core.match_filter.html).

Note that save in this instance should either be False, or a string of the filename.  Annoyingly the docs don't say that - I will update the usage to be consistent with other functions.

**Comment by xiansch** [comment]
I haven't used match_filter yet, just template_gen.  I specified Qt4Agg because otherwise I get an error about Python not being installed as a framework.

The call to template_gen is 
templates = template_gen.from_sac(sac_files=['/Users/schu3/Documents/Japan/temp_test/test1.iweh.U.sac'], lowcut=3.0, highcut=0.0, samp_rate=20.0, filt_order=4, length=80, swin='P', prepick=5.0, debug=0, plot=True)
(added in a lowcut only option using obspy, so the highcut is not used.)

Also I have commented out plt.close() in plotting.pretty_template_plot because I thought that it might be that the plots closed as soon as they showed, but this doesn't seem to make a difference.

Thanks.

**Comment by calum-chamberlain** [comment]
Okay, are you able to view other simple plots? It sounds to me like an issue with your Python install, see link [here](http://stackoverflow.com/questions/4130355/python-matplotlib-framework-under-macosx), but if you can view other plots then that wouldn't be true.

I usually use the TkAgg backend on osx and Ubuntu. Can you provide me with more details of your system and installation of Python?

On Apr 1, 2016 7:23 AM, xiansch <notifications@github.com> wrote:

I haven't used match_filter yet, just template_gen. I specified Qt4Agg because otherwise I get an error about Python not being installed as a framework.

The call to template_gen is
templates = template_gen.from_sac(sac_files=['/Users/schu3/Documents/Japan/temp_test/test1.iweh.U.sac'], lowcut=3.0, highcut=0.0, samp_rate=20.0, filt_order=4, length=80, swin='P', prepick=5.0, debug=0, plot=True)
(added in a lowcut only option using obspy, so the highcut is not used.)

Also I have commented out plt.close() in plotting.pretty_template_plot because I thought that it might be that the plots closed as soon as they showed, but this doesn't seem to make a difference.

Thanks.

-

**Comment by calum-chamberlain** [comment]
Just trying to replicate it now on my Mac. Unfortunately both myself and Chet are away from the office at the moment so it might take a little longer to get to the bottom of it!

**Comment by calum-chamberlain** [comment]
Looks like it's an issue when you only use one trace, I will patch it and let you know!

**Comment by calum-chamberlain** [comment]
Patched in [this commit](https://github.com/calum-chamberlain/EQcorrscan/commit/73a9596e9ac2c6c6653037296ee914cdcdfc2ed7) and tested. 

It would be worth cloning the development branch and running:
`python setup.py install`
from the top directory.

Apologies for this - I rarely try to use single channel templates.

**Comment by calum-chamberlain** [comment]
I just updated also to provide lowpass and high pass filters without you needing to write them in, if you set highcut=None then it will apply a lowpass, commit [here](cbb0d032c34034e5a1d3f7559c83272ee5a00283)

**Comment by xiansch** [comment]
Thanks, this is very helpful!
