### ISSUE TITLE
single_channel_multiplot takes catalog - match_filter outputs detections

### ISSUE THREAD

**Issue by calum-chamberlain** [calum-chamberlain/EQcorrscan#31]
Pointed out by @xiansch
We need to make match_filter output obspy catalog objects, and ensure that everything uses that consistent type...

**Comment by cjhopp** [comment]
New commit here: a8a685e

@xiansch, this should allow you to output an obspy.Catalog from match_filter, although, as multi_event_singlechan() is written, that catalog will need to be modified by the user to make it suitable for plotting. Currently, multi_event_singlechan() takes only catalogs with events that have only one pick. This should be fixed in the plotting function, so this issue should stay open until that's fixed.

**Comment by calum-chamberlain** [comment]
[Committed here](https://github.com/calum-chamberlain/EQcorrscan/commit/b1542bb3f17fecc10a4343aac4acc8d7ec63d0f8) - note that I haven't tested it, but I know how I would - just thought @xiansch might want to give it a go first as I won't have a chance to test it til NZ tomorrow.
